package fr.bull.csg.promethee;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

public class Index extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
   private VerticalLayout mainLayout;
   @AutoGenerated
   private HorizontalLayout horizontalLayout_1;
   @AutoGenerated
   private VerticalLayout verticalLayout_2;
   @AutoGenerated
   private Table table_3;
   @AutoGenerated
   private Label label_3;
   @AutoGenerated
   private Table table_2;
   @AutoGenerated
   private Label label_1;
   @AutoGenerated
   private Table table_1;
   @AutoGenerated
   private Label label_2;
   @AutoGenerated
   private VerticalLayout verticalLayout_1;
   @AutoGenerated
   private Link link_3;
   @AutoGenerated
   private Link link_2;
   @AutoGenerated
   private Link link_1;
   @AutoGenerated
   private Label label1;
   @AutoGenerated
   private NativeButton nativeButton_1;
   /**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Index() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
   private VerticalLayout buildMainLayout()
   {
      // common part: create layout
      mainLayout = new VerticalLayout();
      mainLayout.setImmediate(false);
      mainLayout.setWidth("100%");
      mainLayout.setHeight("100%");
      mainLayout.setMargin(false);
      
      // top-level component properties
      setWidth("100.0%");
      setHeight("100.0%");
      
      // horizontalLayout_1
      horizontalLayout_1 = buildHorizontalLayout_1();
      mainLayout.addComponent(horizontalLayout_1);
      
      return mainLayout;
   }

   @AutoGenerated
   private HorizontalLayout buildHorizontalLayout_1()
   {
      // common part: create layout
      horizontalLayout_1 = new HorizontalLayout();
      horizontalLayout_1.setImmediate(false);
      horizontalLayout_1.setWidth("-1px");
      horizontalLayout_1.setHeight("-1px");
      horizontalLayout_1.setMargin(false);
      
      // verticalLayout_1
      verticalLayout_1 = buildVerticalLayout_1();
      horizontalLayout_1.addComponent(verticalLayout_1);
      horizontalLayout_1.setComponentAlignment(verticalLayout_1, new Alignment(20));
      
      // verticalLayout_2
      verticalLayout_2 = buildVerticalLayout_2();
      horizontalLayout_1.addComponent(verticalLayout_2);
      
      return horizontalLayout_1;
   }

   @AutoGenerated
   private VerticalLayout buildVerticalLayout_1()
   {
      // common part: create layout
      verticalLayout_1 = new VerticalLayout();
      verticalLayout_1.setImmediate(false);
      verticalLayout_1.setWidth("-1px");
      verticalLayout_1.setHeight("-1px");
      verticalLayout_1.setMargin(false);
      
      // nativeButton_1
      nativeButton_1 = new NativeButton();
      nativeButton_1.setCaption("Créer un Build");
      nativeButton_1.setImmediate(true);
      nativeButton_1.setWidth("-1px");
      nativeButton_1.setHeight("-1px");
      verticalLayout_1.addComponent(nativeButton_1);
      
      // label1
      label1 = new Label();
      label1.setImmediate(false);
      label1.setWidth("-1px");
      label1.setHeight("-1px");
      label1.setValue("Branches Disponibles");
      verticalLayout_1.addComponent(label1);
      
      // link_1
      link_1 = new Link();
      link_1.setCaption("trunk V4 (4.13.1)");
      link_1.setImmediate(false);
      link_1.setWidth("-1px");
      link_1.setHeight("-1px");
      verticalLayout_1.addComponent(link_1);
      
      // link_2
      link_2 = new Link();
      link_2.setCaption("trunk V5 (5.2.0)");
      link_2.setImmediate(false);
      link_2.setWidth("-1px");
      link_2.setHeight("-1px");
      verticalLayout_1.addComponent(link_2);
      
      // link_3
      link_3 = new Link();
      link_3.setCaption("prod 4.12.6");
      link_3.setImmediate(false);
      link_3.setWidth("-1px");
      link_3.setHeight("-1px");
      verticalLayout_1.addComponent(link_3);
      
      return verticalLayout_1;
   }

   @AutoGenerated
   private VerticalLayout buildVerticalLayout_2()
   {
      // common part: create layout
      verticalLayout_2 = new VerticalLayout();
      verticalLayout_2.setImmediate(false);
      verticalLayout_2.setWidth("-1px");
      verticalLayout_2.setHeight("-1px");
      verticalLayout_2.setMargin(false);
      
      // label_2
      label_2 = new Label();
      label_2.setImmediate(false);
      label_2.setWidth("-1px");
      label_2.setHeight("-1px");
      label_2.setValue("trunk V4 (4.13.1)");
      verticalLayout_2.addComponent(label_2);
      
      // table_1
      table_1 = new Table();
      table_1.setImmediate(false);
      table_1.setWidth("-1px");
      table_1.setHeight("-1px");
      verticalLayout_2.addComponent(table_1);
      
      // label_1
      label_1 = new Label();
      label_1.setImmediate(false);
      label_1.setWidth("-1px");
      label_1.setHeight("-1px");
      label_1.setValue("trunk V5 (5.2.0)");
      verticalLayout_2.addComponent(label_1);
      
      // table_2
      table_2 = new Table();
      table_2.setImmediate(false);
      table_2.setWidth("-1px");
      table_2.setHeight("-1px");
      verticalLayout_2.addComponent(table_2);
      
      // label_3
      label_3 = new Label();
      label_3.setImmediate(false);
      label_3.setWidth("-1px");
      label_3.setHeight("-1px");
      label_3.setValue("prod 4.12.6");
      verticalLayout_2.addComponent(label_3);
      
      // table_3
      table_3 = new Table();
      table_3.setImmediate(false);
      table_3.setWidth("-1px");
      table_3.setHeight("-1px");
      verticalLayout_2.addComponent(table_3);
      
      return verticalLayout_2;
   }

}
